In [54]:
import numpy as np
import sklearn
from sklearn import datasets
import pandas as pd

In [55]:
energy=pd.read_csv('NewFile4.csv')

In [56]:
Y= energy.ix[:, ['kWh']].copy()

In [57]:
X = energy.ix[: ,['Month','Day','DayOfWeek','Weekday','PeakHour','temp']].copy()

In [58]:
#Split the data into training and testing
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state=0)

#Fit a linear regression model
from sklearn import linear_model

In [59]:
lm=linear_model.LinearRegression()

In [60]:
lm.fit (X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [61]:
lm.coef_

array([[ -6.23374071e-01,  -3.74993726e-01,  -7.28443476e+00,
          5.78347950e+01,   1.09800692e+02,  -2.88739843e-02]])

In [62]:
train_pred = lm.predict(X_train)

In [63]:
#R-squared score of this model
from sklearn.metrics import *
r2_score(y_train, train_pred)

0.59665922545845551

In [64]:
test_pred = lm.predict(X_test)

In [65]:
lm.intercept_

array([ 78.51458147])

In [66]:
test_pred = lm.predict(X_test)

In [67]:
#Mean absolute error
mean_absolute_error(y_test, test_pred)

42.412978900071572

In [68]:
#Mean squared error
mean_squared_error(y_test, test_pred)

2625.7460683020545

In [69]:
#Median absolute error
median_absolute_error(y_test, test_pred)

39.012244226651667

In [70]:
#from sklearn.utils import check_array

In [71]:
#def mean_absolute_percentage_error(y_test, test_pred): 
  #  y_test, test_pred = check_array(y_test, test_pred)
    #return np.mean(np.abs((y_test - test_pred) / y_test)) * 100

In [72]:
#mean_absolute_percentage_error(y_test, test_pred)

In [73]:
## abhijeet insert code to create RegressionOutputs.csv, PerformanceMetrics.csv

In [74]:
#3.a
forecast=pd.read_csv('forecastData.csv')

In [75]:
forecast['Day'] = pd.to_datetime(forecast.ix[:, 'Day'])

In [76]:
forecast = forecast.rename(columns = {'Day':'Date'})

In [77]:
forecast

          Date  Hr  Temp
0   2016-05-25  15    71
1   2016-05-25  16    73
2   2016-05-25  17    77
3   2016-05-25  18    83
4   2016-05-25  19    81
5   2016-05-25  20    79
6   2016-05-25  21    77
7   2016-05-25  22    74
8   2016-05-25  23    73
9   2016-05-26   0    72
10  2016-05-26   1    71
11  2016-05-26   2    70
12  2016-05-26   3    68
13  2016-05-26   4    67
14  2016-05-26   5    66
15  2016-05-26   6    66
16  2016-05-26   7    68
17  2016-05-26   8    71
18  2016-05-26   9    73
19  2016-05-26  10    73
20  2016-05-26  11    73
21  2016-05-26  12    75
22  2016-05-26  13    75
23  2016-05-26  14    76
24  2016-05-26  15    76
25  2016-05-26  16    75
26  2016-05-26  17    74
27  2016-05-26  18    74
28  2016-05-26  19    72
29  2016-05-26  20    70
..         ...  ..   ...
123 2016-05-30  18    72
124 2016-05-30  19    70
125 2016-05-30  20    70
126 2016-05-30  21    68
127 2016-05-30  22    67
128 2016-05-30  23    66
129 2016-05-31   0    66
130 2016-05-31   1    65
131 2016-05-31   2    65
132 2016-05-31   3    64
133 2016-05-31   4    64
134 2016-05-31   5    64
135 2016-05-31   6    64
136 2016-05-31   7    66
137 2016-05-31   8    69
138 2016-05-31   9    71
139 2016-05-31  10    71
140 2016-05-31  11    72
141 2016-05-31  12    74
142 2016-05-31  13    75
143 2016-05-31  14    76
144 2016-05-31  15    76
145 2016-05-31  16    78
146 2016-05-31  17    78
147 2016-05-31  18    76
148 2016-05-31  19    74
149 2016-05-31  20    72
150 2016-05-31  21    70
151 2016-05-31  22    70
152 2016-05-31  23    69

[153 rows x 3 columns]

In [78]:
forecast['Month'] = forecast['Date'].dt.month
forecast['Day'] = forecast['Date'].dt.day
forecast['Year'] = forecast['Date'].dt.year
forecast['DayOfWeek'] = forecast['Date'].dt.weekday+1

In [79]:
def f(x):
    if x['DayOfWeek'] > 5:
        return 0
    else:
        return 1

In [80]:
forecast['Weekday']=forecast.apply(f, axis=1)

In [81]:
def f1(x):
    if x['Hr'] > 6 and x['Hr'] < 20 :
        return 1
    else:
        return 0

In [82]:
forecast['PeakHour']=forecast.apply(f1, axis=1)

In [83]:
cols = list(forecast)

In [84]:
cols.insert(0, cols.pop(cols.index('Date')))
cols.insert(1, cols.pop(cols.index('Month')))
cols.insert(2, cols.pop(cols.index('Day')))
cols.insert(3, cols.pop(cols.index('Year')))
cols.insert(4, cols.pop(cols.index('Hr')))
cols.insert(5, cols.pop(cols.index('DayOfWeek')))
cols.insert(6, cols.pop(cols.index('Weekday')))
cols.insert(7, cols.pop(cols.index('PeakHour')))
cols.insert(8, cols.pop(cols.index('Temp')))
cols

['Date',
 'Month',
 'Day',
 'Year',
 'Hr',
 'DayOfWeek',
 'Weekday',
 'PeakHour',
 'Temp']

In [85]:
forecast = forecast.ix[:, cols]
forecast

          Date  Month  Day  Year  Hr  DayOfWeek  Weekday  PeakHour  Temp
0   2016-05-25      5   25  2016  15          3        1         1    71
1   2016-05-25      5   25  2016  16          3        1         1    73
2   2016-05-25      5   25  2016  17          3        1         1    77
3   2016-05-25      5   25  2016  18          3        1         1    83
4   2016-05-25      5   25  2016  19          3        1         1    81
5   2016-05-25      5   25  2016  20          3        1         0    79
6   2016-05-25      5   25  2016  21          3        1         0    77
7   2016-05-25      5   25  2016  22          3        1         0    74
8   2016-05-25      5   25  2016  23          3        1         0    73
9   2016-05-26      5   26  2016   0          4        1         0    72
10  2016-05-26      5   26  2016   1          4        1         0    71
11  2016-05-26      5   26  2016   2          4        1         0    70
12  2016-05-26      5   26  2016   3          4        1         0    68
13  2016-05-26      5   26  2016   4          4        1         0    67
14  2016-05-26      5   26  2016   5          4        1         0    66
15  2016-05-26      5   26  2016   6          4        1         0    66
16  2016-05-26      5   26  2016   7          4        1         1    68
17  2016-05-26      5   26  2016   8          4        1         1    71
18  2016-05-26      5   26  2016   9          4        1         1    73
19  2016-05-26      5   26  2016  10          4        1         1    73
20  2016-05-26      5   26  2016  11          4        1         1    73
21  2016-05-26      5   26  2016  12          4        1         1    75
22  2016-05-26      5   26  2016  13          4        1         1    75
23  2016-05-26      5   26  2016  14          4        1         1    76
24  2016-05-26      5   26  2016  15          4        1         1    76
25  2016-05-26      5   26  2016  16          4        1         1    75
26  2016-05-26      5   26  2016  17          4        1         1    74
27  2016-05-26      5   26  2016  18          4        1         1    74
28  2016-05-26      5   26  2016  19          4        1         1    72
29  2016-05-26      5   26  2016  20          4        1         0    70
..         ...    ...  ...   ...  ..        ...      ...       ...   ...
123 2016-05-30      5   30  2016  18          1        1         1    72
124 2016-05-30      5   30  2016  19          1        1         1    70
125 2016-05-30      5   30  2016  20          1        1         0    70
126 2016-05-30      5   30  2016  21          1        1         0    68
127 2016-05-30      5   30  2016  22          1        1         0    67
128 2016-05-30      5   30  2016  23          1        1         0    66
129 2016-05-31      5   31  2016   0          2        1         0    66
130 2016-05-31      5   31  2016   1          2        1         0    65
131 2016-05-31      5   31  2016   2          2        1         0    65
132 2016-05-31      5   31  2016   3          2        1         0    64
133 2016-05-31      5   31  2016   4          2        1         0    64
134 2016-05-31      5   31  2016   5          2        1         0    64
135 2016-05-31      5   31  2016   6          2        1         0    64
136 2016-05-31      5   31  2016   7          2        1         1    66
137 2016-05-31      5   31  2016   8          2        1         1    69
138 2016-05-31      5   31  2016   9          2        1         1    71
139 2016-05-31      5   31  2016  10          2        1         1    71
140 2016-05-31      5   31  2016  11          2        1         1    72
141 2016-05-31      5   31  2016  12          2        1         1    74
142 2016-05-31      5   31  2016  13          2        1         1    75
143 2016-05-31      5   31  2016  14          2        1         1    76
144 2016-05-31      5   31  2016  15          2        1         1    76
145 2016-05-31      5   31  2016  16          2        1         1    78
146 2016-05-31      5   31  2016  17          2        1         1    78
147 2016-05-31      5   31  2016  18          2        1         1    76
148 2016-05-31      5   31  2016  19          2        1         1    74
149 2016-05-31      5   31  2016  20          2        1         0    72
150 2016-05-31      5   31  2016  21          2        1         0    70
151 2016-05-31      5   31  2016  22          2        1         0    70
152 2016-05-31      5   31  2016  23          2        1         0    69

[153 rows x 9 columns]

In [86]:
forecast.to_csv('/Users/rheakagti/Desktop/forecastInput.csv', index=False)

In [87]:
#3.b

In [90]:
checkdata=pd.read_csv('forecastInput.csv')

In [91]:
checkdata

           Date  Month  Day  Year  Hr  DayOfWeek  Weekday  PeakHour  Temp
0    2016-05-25      5   25  2016  15          3        1         1    71
1    2016-05-25      5   25  2016  16          3        1         1    73
2    2016-05-25      5   25  2016  17          3        1         1    77
3    2016-05-25      5   25  2016  18          3        1         1    83
4    2016-05-25      5   25  2016  19          3        1         1    81
5    2016-05-25      5   25  2016  20          3        1         0    79
6    2016-05-25      5   25  2016  21          3        1         0    77
7    2016-05-25      5   25  2016  22          3        1         0    74
8    2016-05-25      5   25  2016  23          3        1         0    73
9    2016-05-26      5   26  2016   0          4        1         0    72
10   2016-05-26      5   26  2016   1          4        1         0    71
11   2016-05-26      5   26  2016   2          4        1         0    70
12   2016-05-26      5   26  2016   3          4        1         0    68
13   2016-05-26      5   26  2016   4          4        1         0    67
14   2016-05-26      5   26  2016   5          4        1         0    66
15   2016-05-26      5   26  2016   6          4        1         0    66
16   2016-05-26      5   26  2016   7          4        1         1    68
17   2016-05-26      5   26  2016   8          4        1         1    71
18   2016-05-26      5   26  2016   9          4        1         1    73
19   2016-05-26      5   26  2016  10          4        1         1    73
20   2016-05-26      5   26  2016  11          4        1         1    73
21   2016-05-26      5   26  2016  12          4        1         1    75
22   2016-05-26      5   26  2016  13          4        1         1    75
23   2016-05-26      5   26  2016  14          4        1         1    76
24   2016-05-26      5   26  2016  15          4        1         1    76
25   2016-05-26      5   26  2016  16          4        1         1    75
26   2016-05-26      5   26  2016  17          4        1         1    74
27   2016-05-26      5   26  2016  18          4        1         1    74
28   2016-05-26      5   26  2016  19          4        1         1    72
29   2016-05-26      5   26  2016  20          4        1         0    70
..          ...    ...  ...   ...  ..        ...      ...       ...   ...
123  2016-05-30      5   30  2016  18          1        1         1    72
124  2016-05-30      5   30  2016  19          1        1         1    70
125  2016-05-30      5   30  2016  20          1        1         0    70
126  2016-05-30      5   30  2016  21          1        1         0    68
127  2016-05-30      5   30  2016  22          1        1         0    67
128  2016-05-30      5   30  2016  23          1        1         0    66
129  2016-05-31      5   31  2016   0          2        1         0    66
130  2016-05-31      5   31  2016   1          2        1         0    65
131  2016-05-31      5   31  2016   2          2        1         0    65
132  2016-05-31      5   31  2016   3          2        1         0    64
133  2016-05-31      5   31  2016   4          2        1         0    64
134  2016-05-31      5   31  2016   5          2        1         0    64
135  2016-05-31      5   31  2016   6          2        1         0    64
136  2016-05-31      5   31  2016   7          2        1         1    66
137  2016-05-31      5   31  2016   8          2        1         1    69
138  2016-05-31      5   31  2016   9          2        1         1    71
139  2016-05-31      5   31  2016  10          2        1         1    71
140  2016-05-31      5   31  2016  11          2        1         1    72
141  2016-05-31      5   31  2016  12          2        1         1    74
142  2016-05-31      5   31  2016  13          2        1         1    75
143  2016-05-31      5   31  2016  14          2        1         1    76
144  2016-05-31      5   31  2016  15          2        1         1    76
145  2016-05-31      5   31  2016  16          2        1         1    78
146  2016-05-31      5   31  2016  17          2        1         1    78
147  2016-05-31      5   31  2016  18          2        1         1    76
148  2016-05-31      5   31  2016  19          2        1         1    74
149  2016-05-31      5   31  2016  20          2        1         0    72
150  2016-05-31      5   31  2016  21          2        1         0    70
151  2016-05-31      5   31  2016  22          2        1         0    70
152  2016-05-31      5   31  2016  23          2        1         0    69

[153 rows x 9 columns]

In [92]:
X_test2 = checkdata.ix[: ,['Month','Day','DayOfWeek','Weekday','PeakHour','Temp']].copy()
X_test2

     Month  Day  DayOfWeek  Weekday  PeakHour  Temp
0        5   25          3        1         1    71
1        5   25          3        1         1    73
2        5   25          3        1         1    77
3        5   25          3        1         1    83
4        5   25          3        1         1    81
5        5   25          3        1         0    79
6        5   25          3        1         0    77
7        5   25          3        1         0    74
8        5   25          3        1         0    73
9        5   26          4        1         0    72
10       5   26          4        1         0    71
11       5   26          4        1         0    70
12       5   26          4        1         0    68
13       5   26          4        1         0    67
14       5   26          4        1         0    66
15       5   26          4        1         0    66
16       5   26          4        1         1    68
17       5   26          4        1         1    71
18       5   26          4        1         1    73
19       5   26          4        1         1    73
20       5   26          4        1         1    73
21       5   26          4        1         1    75
22       5   26          4        1         1    75
23       5   26          4        1         1    76
24       5   26          4        1         1    76
25       5   26          4        1         1    75
26       5   26          4        1         1    74
27       5   26          4        1         1    74
28       5   26          4        1         1    72
29       5   26          4        1         0    70
..     ...  ...        ...      ...       ...   ...
123      5   30          1        1         1    72
124      5   30          1        1         1    70
125      5   30          1        1         0    70
126      5   30          1        1         0    68
127      5   30          1        1         0    67
128      5   30          1        1         0    66
129      5   31          2        1         0    66
130      5   31          2        1         0    65
131      5   31          2        1         0    65
132      5   31          2        1         0    64
133      5   31          2        1         0    64
134      5   31          2        1         0    64
135      5   31          2        1         0    64
136      5   31          2        1         1    66
137      5   31          2        1         1    69
138      5   31          2        1         1    71
139      5   31          2        1         1    71
140      5   31          2        1         1    72
141      5   31          2        1         1    74
142      5   31          2        1         1    75
143      5   31          2        1         1    76
144      5   31          2        1         1    76
145      5   31          2        1         1    78
146      5   31          2        1         1    78
147      5   31          2        1         1    76
148      5   31          2        1         1    74
149      5   31          2        1         0    72
150      5   31          2        1         0    70
151      5   31          2        1         0    70
152      5   31          2        1         0    69

[153 rows x 6 columns]

In [93]:
test_pred2 = lm.predict(X_test)

In [94]:
test_pred2

array([[ 101.5780067 ],
       [ 100.29900094],
       [ 211.62554146],
       ...,
       [ 193.22078621],
       [ 219.13517831],
       [ 214.46151896]])